[build]
  command = "npm run build"
  publish = "_site"
  functions = "functions"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/rdm/*"
  status = 200
  force = true
  conditions = {Role = ["admin"]}
